import { fontFamilyHeadings, fontFamilyBody } from './nomenclaturaGeneral'; 
const styles = {
  
  sidebar: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '250px',
    height: '100vh',
    backgroundColor: '#F2F4F4',
    padding: '20px',
    color: '#34495E',
    boxShadow: '2px 0 15px rgba(0, 0, 0, 0.1)',
    fontFamily: fontFamilyBody, 
    zIndex: 1000,
    display: 'flex',
    flexDirection: 'column',
    transition: 'transform 0.3s ease-in-out',
     position: 'fixed',
  },
  header: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    marginBottom: '30px',
    borderBottom: '1px solid #E5E7E9',
    paddingBottom: '20px',
  },
  logo: {
    width: '70%',
    maxWidth: '180px',
    marginBottom: '15px',
  },
  title: {
    fontFamily: fontFamilyHeadings, 
    fontSize: '22px',
    fontWeight: 'bold',
    color: '#33538B',
  },
  toggleButton: {
    position: 'fixed',
    top: '15px',
    left: '15px',
    backgroundColor: '#33538B',
    color: '#FFFFFF',
    border: 'none',
    borderRadius: '50%',
    width: '45px',
    height: '45px',
    cursor: 'pointer',
    zIndex: 1001,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
  },
  toggleIcon: {
    fontSize: '20px',
  },
  closeButton: {
    position: 'absolute',
    right: '-25px',
    top: '50%',
    width: '25px',
    height: '100px',
    backgroundColor: '#33538B',
    color: '#FFFFFF',
    border: 'none',
    padding: '0',
    fontSize: '24px',
    cursor: 'pointer',
    zIndex: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '0 8px 8px 0',
    transform: 'translateY(-50%)',
  },
  closeIcon: {
    fontSize: '16px',
  },
  menu: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
    flex: 1,
  },
  menuItem: {
    fontFamily: fontFamilyBody, 
    display: 'flex',
    alignItems: 'center',
    gap: '15px',
    padding: '12px 15px',
    color: '#34495E',
    textDecoration: 'none',
    fontSize: '16px',
    borderRadius: '8px',
    transition: 'background-color 0.2s, color 0.2s',
    marginBottom: '8px',
    fontWeight: '500',
  },
  menuItemHover: {
    backgroundColor: '#E5E7E9',
    color: '#33538B',
  },
  icon: {
    fontSize: '20px',
  },
};

export default styles;